import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.9

[window.padding]
x = 25
y = 20

[font]
size = 14.5

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[[keyboard.bindings]]
chars = "\u006c\u0061\u007a\u0079\u0067\u0069\u0074\u000a"
key = "G"
mods = "Command"
