# Brewfile
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"

brew "firebase-cli"
brew "awscli"
brew "tree-sitter"
brew "cask"

brew "ruby"
brew "rbenv"

brew "cocoapods"
brew "neovim"
brew "lazygit"

brew "go"
brew "gopls"

brew "ripgrep"
brew "eza"
brew "ghq"
brew "fzf"
brew "fd"
brew "tmux"
brew "git"

brew "lua-language-server"

brew "nvm"
brew "pnpm"

brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

brew "tflint"
brew "hashicorp/tap/terraform"
brew "hashicorp/tap/terraform-ls"

cask "slack" 
cask "1password"
cask "typora"
cask "iterm2"
cask "arc"
cask "google-chrome"
cask "datagrip"
cask "postman"
cask "flutter"
cask "docker"
cask "android-studio"
cask "notion"
cask "temurin"
cask "figma"
cask "zed"
cask "devtoys"
cask "raycast"
cask "font-jetbrains-mono-nerd-font"
cask "font-symbols-only-nerd-font"
