require("config.lazy")
require("plugins")

require("webchemist.alpha")
require("webchemist.autopairs")
require("webchemist.bufferline")
require("webchemist.flutter-tools")
require("webchemist.git")
require("webchemist.hop")
require("webchemist.lualine")
require("webchemist.lsp")
require("webchemist.neotree")
require("webchemist.neotest")
require("webchemist.telescope")
require("webchemist.toggleterm")
require("webchemist.treesitter")
require("webchemist.undotree")

require("whichkey")
