auth_type: basic
board:
    id: 6
    name: WEB 보드
    type: simple
epic:
    name: customfield_10011
    link: customfield_10014
installation: Cloud
issue:
    fields:
        custom:
            - name: Time to resolution
              key: customfield_10060
              schema:
                datatype: sd-servicelevelagreement
            - name: Time to first response
              key: customfield_10061
              schema:
                datatype: sd-servicelevelagreement
            - name: Time to close after resolution
              key: customfield_10062
              schema:
                datatype: sd-servicelevelagreement
            - name: Time to review normal change
              key: customfield_10063
              schema:
                datatype: sd-servicelevelagreement
            - name: 목표
              key: customfield_10064
              schema:
                datatype: array
                items: 목표
            - name: Affected hardware
              key: customfield_10050
              schema:
                datatype: string
            - name: Planned start
              key: customfield_10051
              schema:
                datatype: datetime
            - name: Planned end
              key: customfield_10052
              schema:
                datatype: datetime
            - name: Implementation plan
              key: customfield_10053
              schema:
                datatype: string
            - name: Backout plan
              key: customfield_10054
              schema:
                datatype: string
            - name: Test plan
              key: customfield_10055
              schema:
                datatype: string
            - name: Source
              key: customfield_10056
              schema:
                datatype: option
            - name: Investigation reason
              key: customfield_10057
              schema:
                datatype: option
            - name: Root cause
              key: customfield_10058
              schema:
                datatype: string
            - name: Workaround
              key: customfield_10059
              schema:
                datatype: string
            - name: Severity
              key: customfield_10049
              schema:
                datatype: option
            - name: Satisfaction date
              key: customfield_10040
              schema:
                datatype: datetime
            - name: Approvals
              key: customfield_10041
              schema:
                datatype: sd-approvals
            - name: Request language
              key: customfield_10042
              schema:
                datatype: sd-request-lang
            - name: Urgency
              key: customfield_10043
              schema:
                datatype: option
            - name: Affected services
              key: customfield_10044
              schema:
                datatype: array
                items: service-entity-field
            - name: Pending reason
              key: customfield_10045
              schema:
                datatype: option
            - name: Approver groups
              key: customfield_10046
              schema:
                datatype: array
                items: group
            - name: Major incident
              key: customfield_10047
              schema:
                datatype: string
            - name: Responders
              key: customfield_10048
              schema:
                datatype: array
                items: string
            - name: Request participants
              key: customfield_10038
              schema:
                datatype: array
                items: user
            - name: Satisfaction
              key: customfield_10039
              schema:
                datatype: sd-feedback
            - name: Vulnerability
              key: customfield_10030
              schema:
                datatype: any
            - name: Sentiment
              key: customfield_10031
              schema:
                datatype: array
                items: sd-sentiment
            - name: Project overview key
              key: customfield_10032
              schema:
                datatype: string
            - name: Project overview status
              key: customfield_10033
              schema:
                datatype: string
            - name: Design
              key: customfield_10034
              schema:
                datatype: array
                items: design.field.name
            - name: 범주
              key: customfield_10035
              schema:
                datatype: option
            - name: Story Points
              key: customfield_10036
              schema:
                datatype: number
            - name: 작업 범주
              key: customfield_10037
              schema:
                datatype: string
            - name: 열린 양식
              key: customfield_10027
              schema:
                datatype: number
            - name: 제출한 양식
              key: customfield_10028
              schema:
                datatype: number
            - name: 전체 양식
              key: customfield_10029
              schema:
                datatype: number
            - name: Sprint
              key: customfield_10020
              schema:
                datatype: array
                items: json
            - name: Flagged
              key: customfield_10021
              schema:
                datatype: array
                items: option
            - name: Target start
              key: customfield_10022
              schema:
                datatype: date
            - name: Target end
              key: customfield_10023
              schema:
                datatype: date
            - name: '[CHART] Date of First Response'
              key: customfield_10024
              schema:
                datatype: datetime
            - name: '[CHART] Time in Status'
              key: customfield_10025
              schema:
                datatype: any
            - name: 잠긴 양식
              key: customfield_10026
              schema:
                datatype: number
            - name: Story point estimate
              key: customfield_10016
              schema:
                datatype: number
            - name: Issue color
              key: customfield_10017
              schema:
                datatype: string
            - name: Parent Link
              key: customfield_10018
              schema:
                datatype: any
            - name: Rank
              key: customfield_10019
              schema:
                datatype: any
            - name: Request Type
              key: customfield_10010
              schema:
                datatype: sd-customerrequesttype
            - name: Epic Status
              key: customfield_10012
              schema:
                datatype: option
            - name: Epic Color
              key: customfield_10013
              schema:
                datatype: string
            - name: Start date
              key: customfield_10015
              schema:
                datatype: date
            - name: Change type
              key: customfield_10005
              schema:
                datatype: option
            - name: Change risk
              key: customfield_10006
              schema:
                datatype: option
            - name: Change reason
              key: customfield_10007
              schema:
                datatype: option
            - name: Actual start
              key: customfield_10008
              schema:
                datatype: datetime
            - name: Actual end
              key: customfield_10009
              schema:
                datatype: datetime
            - name: development
              key: customfield_10000
              schema:
                datatype: any
            - name: Team
              key: customfield_10001
              schema:
                datatype: team
            - name: Organizations
              key: customfield_10002
              schema:
                datatype: array
                items: sd-customerorganization
            - name: Approvers
              key: customfield_10003
              schema:
                datatype: array
                items: user
            - name: Impact
              key: customfield_10004
              schema:
                datatype: option
    types:
        - id: "10022"
          name: 작업
          handle: Task
          subtask: false
        - id: "10023"
          name: 버그
          handle: Bug
          subtask: false
        - id: "10024"
          name: 스토리
          handle: Story
          subtask: false
        - id: "10025"
          name: 에픽
          handle: 에픽
          subtask: false
        - id: "10026"
          name: 하위 작업
          handle: 하위 작업
          subtask: true
login: yoonwonyoul@webchemist.net
project:
    key: WEB
    type: next-gen
server: https://webchemist.atlassian.net
timezone: Asia/Seoul
